export const PAYMENT_TOKEN_REQUEST = "PAYMENT_TOKEN_REQUEST";
export const PAYMENT_TOKEN_SUCCESS = "PAYMENT_TOKEN_SUCCESS";
export const PAYMENT_TOKEN_FAIL = "PAYMENT_TOKEN_FAIL";

export const PAYMENT_PROCESS_REQUEST = "PAYMENT_PROCESS_REQUEST";
export const PAYMENT_PROCESS_SUCCESS = "PAYMENT_PROCESS_SUCCESS";
export const PAYMENT_PROCESS_FAIL = "PAYMENT_PROCESS_FAIL";
export const PAYMENT_PROCESS_RESET = "PAYMENT_PROCESS_RESET";
